app/routes/admin.py
from flask import render_template, request, redirect, url_for, send_file, session, Blueprint

from ..forms import *
from ..middleware import admin_required, approve_required
from ..config import Config

admin_bp = Blueprint('admin', __name__)

@admin_bp.route('/login', methods=['GET', 'POST'])
def admin_login():
    form = LoginForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            username = form.username.data
            password = form.password.data
            if username == Config.ADMIN_USERNAME and password == Config.ADMIN_PASSWORD:
                session['admin_logged_in'] = True
                return redirect(url_for('admin.admin_dashboard'))
    return render_template('forms/admin_login.html', form=form)

@admin_bp.route('/logout', methods=['GET'])
@admin_required
def admin_logout():
    # Handle admin logout logic here
    session.pop('admin_logged_in', None)
    return redirect(url_for('admin.admin_login'))


@admin_bp.route('/dashboard')
@admin_required
def admin_dashboard():
    return render_template('admin/index.html')

@admin_bp.route('/dashboard/<string:model>', methods=['GET'])
@admin_required
def admin_dashboard_model(model):
    return render_template('admin/model.html', model=model)

@admin_bp.route('/dashboard/<string:model>/<int:id>', methods=['GET'])
@admin_required
def admin_dashboard_model_instance(model, id):
    return render_template('admin/model_instance.html', model=model, id=id)

@admin_bp.route('/contract', methods=['GET', 'POST'])
@admin_required
def admin_contract():
    form = ContractForm()
    if form.validate_on_submit():
        # Process the contract form data
        return redirect(url_for('admin.admin_dashboard'))
    return render_template('forms/contract.html', form=form)

app/templates/forms/admin_login.html
{% extends "base.html" %}

{% block title %}Admin Login{% endblock %}

{% block content %}
<h2>Admin Login</h2>
<form method="POST">
    {{ form.hidden_tag() }}
    <div>
        {{ form.username.label }}<br>
        {{ form.username }}<br>
        {% for error in form.username.errors %}
        <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
    </div>
    <div>
        {{ form.password.label }}<br>
        {{ form.password(size=32) }}<br>
        {% for error in form.password.errors %}
        <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
    </div>
    <div>
        {{ form.submit() }}
    </div>
</form>
<a href="{{ url_for('admin.admin_logout') }}">Logout</a>
{% endblock %}

app/templates/forms/contract.html
{% extends "base.html" %}

{% block title %}Admin Contract{% endblock %}

{% block content %}
<h2>Admin Contract</h2>
<form method="POST">
    {{ form.hidden_tag() }}
    <div>
        {{ form.client.label }}<br>
        {{ form.client }}<br>
        {% for error in form.client.errors %}
        <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
    </div>
    <div>
        {{ form.seller.label }}<br>
        {{ form.seller }}<br>
        {% for error in form.seller.errors %}
        <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
    </div>
    <div>
        {{ form.date_from.label }}<br>
        {{ form.date_from }}<br>
        {% for error in form.date_from.errors %}
        <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
    </div>
    <div>
        {{ form.date_to.label }}<br>
        {{ form.date_to }}<br>
        {% for error in form.date_to.errors %}
        <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
    </div>
    <div>
        <button type="submit">Submit</button>
    </div>
</form>
{% endblock %}

app/templates/forms/user_login.html
{% extends "base.html" %}

{% block content %}
  <h1>Login with Telegram</h1>
  <script async src="https://telegram.org/js/telegram-widget.js?22" data-telegram-login="cspace_id_bot" data-size="large" data-onauth="onTelegramAuth(user)" data-request-access="write"></script>
  <script type="text/javascript">
    function onTelegramAuth(user) {
      alert('Logged in as ' + user.first_name + ' ' + user.last_name + ' (' + user.id + (user.username ? ', @' + user.username : '') + ')');
    }
  </script>
{% endblock %}